import pony.orm as pony

db = pony.Database()

##In order to decide whether an attribute was optional or not i checked https://www.space-track.org/basicspacedata/modeldef/class/gp/format/html

class Satelite(db.Entity):
    db_id =pony.PrimaryKey(int, auto=True)
    id = pony.Required(str)
    launch = pony.Optional(str)
    version = pony.Optional(str)
    height_km = pony.Optional(float)
    latitude = pony.Optional(float)
    longitude = pony.Optional(float)
    velocity_kms = pony.Optional(float)
    spaceTrack = pony.Required("SpaceTrack", reverse="satelite")

class SpaceTrack(db.Entity):
    db_id =pony.PrimaryKey(int, auto=True)
    satelite = pony.Optional("Satelite", reverse="spaceTrack")
    CCSDS_OMM_VERS = pony.Required(str)
    COMMENT = pony.Required(str)
    CREATION_DATE = pony.Optional(str)
    ORIGINATOR = pony.Required(str)
    OBJECT_NAME = pony.Optional(str)
    OBJECT_ID = pony.Optional(str)
    CENTER_NAME = pony.Required(str)
    REF_FRAME = pony.Required(str)
    TIME_SYSTEM = pony.Required(str)
    MEAN_ELEMENT_THEORY = pony.Required(str)
    EPOCH = pony.Optional(str)
    MEAN_MOTION = pony.Optional(float)
    ECCENTRICITY = pony.Optional(float)
    INCLINATION = pony.Optional(float)
    RA_OF_ASC_NODE = pony.Optional(float)
    ARG_OF_PERICENTER = pony.Optional(float)
    MEAN_ANOMALY = pony.Optional(float)
    EPHEMERIS_TYPE = pony.Optional(int)
    CLASSIFICATION_TYPE = pony.Optional(str)
    NORAD_CAT_ID = pony.Required(int)
    ELEMENT_SET_NO = pony.Optional(int)
    REV_AT_EPOCH = pony.Optional(int)
    BSTAR = pony.Optional(float)
    MEAN_MOTION_DOT = pony.Optional(float)
    MEAN_MOTION_DDOT = pony.Optional(float)
    SEMIMAJOR_AXIS = pony.Optional(float)
    PERIOD = pony.Optional(float)
    APOAPSIS = pony.Optional(float)
    PERIAPSIS = pony.Optional(float)
    OBJECT_TYPE = pony.Optional(str)
    RCS_SIZE = pony.Optional(str)
    COUNTRY_CODE = pony.Optional(str)
    LAUNCH_DATE = pony.Optional(str)
    SITE = pony.Optional(str)
    DECAY_DATE = pony.Optional(str)
    DECAYED = pony.Optional(int)
    FILE = pony.Optional(int)
    GP_ID = pony.Required(int)
    TLE_LINE0 = pony.Optional(str)
    TLE_LINE1 = pony.Optional(str)
    TLE_LINE2 = pony.Optional(str)

db.bind("sqlite", "database.satelite", create_db=True) ## Using sqlite3 as recomended
db.generate_mapping(create_tables=True)
